create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  hostname text not null,
  os text,
  agent_version text,
  status text not null default 'offline' check (status in ('online','offline','warning')),
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.metrics (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  cpu_percent double precision not null,
  memory_percent double precision not null,
  disk_percent double precision not null,
  network_rx_bytes bigint not null default 0,
  network_tx_bytes bigint not null default 0,
  temperature_c double precision,
  load_1m double precision
);

create table if not exists public.anomalies (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  metric_id bigint references public.metrics(id) on delete set null,
  detected_at timestamptz not null default now(),
  metric text not null,
  severity text not null check (severity in ('low','medium','high','critical')),
  score double precision,
  value double precision,
  baseline double precision,
  message text,
  status text not null default 'open' check (status in ('open','acknowledged','resolved'))
);

create table if not exists public.diagnoses (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  anomaly_id bigint references public.anomalies(id) on delete set null,
  created_at timestamptz not null default now(),
  root_cause text,
  confidence double precision,
  summary text not null,
  evidence jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb
);

create index if not exists metrics_device_time_idx on public.metrics(device_id, recorded_at desc);
create index if not exists anomalies_device_time_idx on public.anomalies(device_id, detected_at desc);
create index if not exists diagnoses_device_time_idx on public.diagnoses(device_id, created_at desc);

alter table public.devices enable row level security;
alter table public.metrics enable row level security;
alter table public.anomalies enable row level security;
alter table public.diagnoses enable row level security;

-- Prototype policy: authenticated users only. Production will add device ownership.
grant select, insert, update on public.devices to authenticated;
grant select, insert, update on public.metrics to authenticated;
grant select, insert, update on public.anomalies to authenticated;
grant select, insert, update on public.diagnoses to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "authenticated devices access" on public.devices for all to authenticated using (true) with check (true);
create policy "authenticated metrics access" on public.metrics for all to authenticated using (true) with check (true);
create policy "authenticated anomalies access" on public.anomalies for all to authenticated using (true) with check (true);
create policy "authenticated diagnoses access" on public.diagnoses for all to authenticated using (true) with check (true);
